@startuml provide_feedback_usecase

left to right direction
skinparam backgroundColor #FAFAFA
skinparam shadowing true

skinparam actor {
    BackgroundColor #f9f9f9
    BorderColor Black
    FontColor Black
    Shadowing true
}

skinparam usecase {
    BackgroundColor White
    BorderColor #2C3E50
    ArrowColor #2C3E50
    FontColor Black
    FontSize 12
    Shadowing true
    RoundCorner 20
}

actor Student
actor Instructor
actor Admin

actor Student

rectangle "Feedback System" {
    usecase UC_LoginDashboard as "Log in and access dashboard"
    usecase UC_ViewSurveys as "View available surveys"
    usecase UC_ReadInstructions as "Open and read instructions"
    usecase UC_Respond as "Respond to survey questions"
    usecase UC_AutoSave as "Auto-save progress"
    usecase UC_Submit as "Submit completed survey"
    usecase UC_Confirm as "Receive confirmation message"
}
' Student Flow
Student --> UC_LoginDashboard
Student --> UC_ViewSurveys
Student --> UC_ReadInstructions
Student --> UC_Respond
UC_Respond --> UC_AutoSave : <<include>>
Student --> UC_Submit
Student --> UC_Confirm

    usecase UC_Review as "Access aggregated feedback"
    usecase UC_Logs as "Review system logs and analytics"
    usecase UC_Privacy as "Manage access and compliance"

@enduml
