@startuml Login Use Case Diagram
' Title
title Login Use Case Diagram

' Direction
left to right direction

' Actors
actor Student
actor Instructor
actor Administrator

' Use Cases
rectangle "Login Use Case" {
    usecase "Access Login\nInterface" as UC1
    usecase "Enter\nCredentials" as UC2
    usecase "Verify\nAccount Exists" as UC3
    usecase "Redirect\nto Registration" as UC4
    usecase "Validate\nCredentials" as UC5
    usecase "Redirect\nto Specific Dashboard" as UC6
    usecase "Increment\nFailed Attemps" as UC7
    usecase "Lock\nAccount Temporarily" as UC8
    usecase "Display\nError Message" as UC9
    usecase "Forgot\nPassworrd" as UC10
}

' Actor Relations
Student --> UC1
Instructor --> UC1
Administrator --> UC1

' Use Case Flow
UC1 -.-|> UC10
UC1 --> UC2
UC1 -.-|> UC4
UC2 --> UC3
UC3 --> UC4 : if account doesn't exist
UC3 --> UC5 : if account exists
UC5 --> UC6 : if credentials are valid
UC5 --> UC7 : credentials are invalid
UC5 -.-|> UC10 : credentials are invalid
UC7 -.-|> UC8
UC7 --> UC9 : display warning

' Note for locking logic
note bottom of UC4
Registration system\n
See the registration diagram: UC-Login-Registration.png
end note

note right of UC8
After 3 failed attemps: lock for 1 minute\n
After 5 failed attemps: lock for 3 minutes\n
end note

note bottom of UC10
Recovery system.
See the Recovery diagram: UC-Login-Recovery.png
end note

caption This diagram describes the global login process for all actors.

@enduml